/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=/dev/null --include-runtime=false apps/worker/src/worker-configuration.d.ts` (hash: 2293c946cd0bac985d9f4cd01f646af3)
interface __BaseEnv_Env {
	ASSETS_BUCKET: R2Bucket;
	DB: D1Database;
	MEDIA_ICON_INDEX_REFRESH_QUEUE: Queue;
	ASSETS: Fetcher;
	SETUP_ENABLED: "true";
	RENEWLET_MAINTENANCE_MODE: "false";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SETUP_ENABLED" | "RENEWLET_MAINTENANCE_MODE">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}